### ISSUE TITLE
XCP-ng 8.1 (meta issue)

### ISSUE THREAD

**Issue by stormi** [xcp-ng/xcp#328]
We have reached a first alpha release of XCP-ng 8.1. This meta issue is here to list all that remains to do before the final release.

Before beta:
- [x] UEFI support - secureboot disabled
- [x] Review installer code after conflict solving - https://github.com/xcp-ng/host-installer/issues/15
- [x] Update zstd to 1.4.2 - https://github.com/xcp-ng/xcp/issues/299
- [x] Test zstd import and export - https://github.com/xcp-ng/xcp/issues/299

Before beta (tests):
- [x] Usual checks and tests
- [x] Check fix to xenserver-firstboot: still needed? => yes, still needed
- [x] In yum upgrade, make sure /etc/xensource-inventory is appropriately modified (BUILD_NUMBER)
- [x] Test XFS driver, must still work
- [x] Check fix to xcp-ng-release post scriptlet

Before RC:
- [x] Usual checks and tests
- [x] Test handling of guest tools ISO update and CD eject from VMs - https://github.com/xcp-ng/xcp/issues/282
- [x] Test resolution of EULA screen issue - https://github.com/xcp-ng/xcp/issues/242
- [x] Check/test max_grant_frames since we're removing the xenguest patch. If needed restore the patch.
- [x] Remove warning patch from xsconsole now that it doesn't restart the service anymore? Test yum update from xsconsole. 
- [x] ZFS 0.8.3
- [x] Update zstd to 1.4.4 - https://github.com/xcp-ng/xcp/issues/299
- [x] alternate kernel and its upgrade. Add it back to the list of extra packages.
- [x] alternate modules and their upgrade
- [x] check all extra packages can be installed and upgraded
- [x] build of netdata xenstat plugin (currently fails) - https://github.com/netdata/netdata/issues/7803. Also add it back to the list of extra packages (netdata + netdata-ui).
- [x] look at impact of deprecated dynamic memory: different defaults in templates? Anything else?  
  - => templates have not changed in this regard
  - dynamic min is still twice the static min by default
- [x] Include `https://github.com/xenserver/xe-guest-utilities/pull/75/commits/619cd71eb45b53908e1ee3c10702289e0f1507a7` fix to linux pv tools?
- [x] Check coretemp issue on XCP-ng 8.1 and decide about coretemp-module-alt. Add it back to the list of extra packages if still needed.
- [x] openvswitch-ipsec by default or XO being able to install it via a plugin => we won't have time for 8.1, so we simply add a note in XO if possible https://github.com/vatesfr/xen-orchestra/issues/4753
- [x] missing symlink, causing [Autostart issues](https://xcp-ng.org/forum/topic/2572/xcp-ng-8-1-beta-autostart-vm-s-not-working-and-xencenter-out-of-date)! (upstream bug) - https://bugs.xenserver.org/browse/XSO-978 
- [x] Transition from our experimental EXT4 driver to the now default EXT4 driver in XCP-ng 8.1 - https://github.com/xcp-ng/xcp/issues/327 => through documentation, deprecation notice and forbidding the creation of new ext4 SRs.
- [x] Envision new coalesce patch - https://github.com/xcp-ng/xcp/issues/323
- [x] Patched qlogic-netxtreme2 https://github.com/xcp-ng/xcp/issues/336
- [x] Backport kernel hotfix from CH 8.1 to `kernel`
- [x] Backport kernel hotfix from CH 8.1 to `kernel-alt`? Already there.
- [x] Offer to boot and install kernel-alt https://github.com/xcp-ng/xcp/issues/340
- [x] Add an installation option that uses only 2048 Mb of RAM to workaround Ryzen installation issues (black screen)
- [x] Patched qlogic-netxtreme2 in installer
- [x] netdata default conf: switch to `save` memory mode to avoid dbengine bugs

Before final:
- [x] Check our specific fixes if still specific or if recently merged into CH (and update the list of fixes as a reference for next release)
- [x] Write guide to go from experimental ext4 SR to standard EXT SR
- [x] Usual checks and tests
- [x] Checks related to changes in CH 8.1
- [x] Test new coalesce logic - https://github.com/xcp-ng/xcp/issues/323
- [x] Link upgrade docs to Citrix's known issues
- [x] Study deprecations and plan about the future
- [x] Benchmark OVA export and import with 8.1 and new ZSTD
- [x] Test added multipath config for TrueNAS - https://github.com/xcp-ng/xcp/issues/297
- [x] Update xcp-featured if needed
- [x] Supported Windows PV drivers on tools ISO? - https://github.com/xcp-ng/xcp/issues/324 => we couldn't do it for this release but made tests and updated the Guest tools wiki page.
- [x] Changelog
- [x] Update glusterfs to latest
- [x] Change welcome page regarding XCP-ng Center / or release a new XCP-ng Center before final release
- [x] XS console displays EXT3 for EXT4 SRs (upstream bug)
- [x] ~~run `systemctl preset-all --preset-mode=enable-only` to fix systemd unit deps after upgrade ?~~
- [x] kernel-alt update plan: parallel installable packages or only one that is updated
- [x] Disclaimer on XCP-ng Center DL page
- [x] (with XO) Experimental backups with RAM to replace the broken and now defunct VSS
- [x] Infra: add more disk space to koji
- [x] Fix UEFI + netinstall (should not offer local media option) https://github.com/xcp-ng/xcp
/issues/348
- [x] Go through the above and document what needs documenting

After the release:
- [ ] Infra: update mirrorbits scripts to deal with GeoLite2 distribution changes - https://github.com/xcp-ng/xcp/issues/322
- [ ] CentOS security updates
- [x] EOL XCP-ng 7.6

Not for 8.1:
- [ ] UEFI support - secureboot enabled
- [ ] HTTPS support for vm.import - https://github.com/xcp-ng/xcp/issues/318
- [ ] USB passthrough issues - https://github.com/xcp-ng/xcp/issues/125
- [ ] Harmonisation of success and error reporting in xcp-ng-xapi-plugins - https://github.com/xcp-ng/xcp/issues/246
- [ ] Try to fix installer boot issue on hardware with Ryzen APUs https://github.com/xcp-ng/xcp/issues/206
- [ ] netdata log flood https://github.com/netdata/netdata/issues/8019
- [ ] Fix xcp-ng-build-env for 8.0 and 8.1:  there's no EPEL active by default anymore and there's weird "[Errno 13] Permission denied: '/var/lib/rpm/Basenames'"
- [ ] Update sm with latest "GC interrupted" fix?

**Comment by danieldemoraisgurgel** [comment]
How was this functionality? 
> Check / test max_grant_frames since we're removing the xenguest patch. If needed restore the patch.

**Comment by stormi** [comment]
> How was this functionality?
> 
> > Check / test max_grant_frames since we're removing the xenguest patch. If needed restore the patch.

The patch is not needed anymore. max_grant_frames is handled by xenopsd so it should just work. Feel free to confirm by testing XCP-ng 8.1 beta.
