### ISSUE TITLE
XCP-ng 7.5

### ISSUE THREAD

**Issue by olivierlambert** [xcp-ng/xcp#39]
XenServer 7.5 is now available.

We need to both release a new ISO of XCP-ng **and** a package update for current installs

## Updates

- [x] use and deploy OSS version of EMU manager (@johnelse) #24 
- [x] upload all packages while removing trademarks inside them (@stormi)
- [x] fix release version numbers no updating (7.4 to 7.5) (@stormi)
- [x] fix the `xcp-python-libs-2.0.3-2.noarch` package with the Python script (see https://xcp-ng.org/forum/topic/79/configure-dom0-memory-not-work) (@stormi)
- [x] fix the new v6d API call of XAPI (@johnelse)
- [x] include xcp-ng-center in the xencenter RPM and fix broken link in the HTML welcome page of the server (@stormi)
- [x] create new repository structure (@stormi)
- [x] change repository configuration at update time (@stormi)
- [x] provide source RPMs (@stormi)
- [x] enforce installation of xcp-ng-updater during update, or document a way to install it (@stormi)
- [x] check whether yum update is sufficient or a special package with upgrade scripts is needed (for configuration files or other things)
- [x] experimental ZFS support + a way to install it / get back to previous state (even if it's just documentation)
- [x] update version of xcp-ng-center if a newer is available at the time of release (@stormi)
- [x] create tags and releases to our git software repositories and create branches and tags to our git RPM source repositories.
- [x] add instructions for yum upgrade (repository file changed) (@stormi)

## New ISO

- [X] embed the missing /etc/shadow file (@stormi) #35 
- [X] update all the product versions (@stormi)
- [x] embed the new EMU manager
- [X] add xcp-ng-updater.rpm (@stormi)
- [x] Fix wording of the EXT vs LVM option for local SR (@stormi) #45 
- [x] Allow update from XS 7.5
- [x] generate the ISO (@stormi)
- [x] upload it

**Comment by skajter** [comment]
Not sure, but better to point: In new iso, also we need include new XenCenter as im not sure that was fixed or not: https://github.com/xcp-ng/xenadmin/issues/38

**Comment by olivierlambert** [comment]
Yes, we'll try to do that, but it's not 100% trivial. Our new recruit is coming soon to work on that :)

**Comment by stormi** [comment]
@skajter new recruit here, and I fixed it. This will be included in 7.5.

**Comment by skajter** [comment]
Also i like to mention about https://github.com/xcp-ng/xcp/issues/30 - as is for old 7.4 version ... not sure that we continue to support, and then the old one will be valid, or we just move on on 7.5, and close one?  :)

**Comment by stormi** [comment]
I'm not sure because @olivierlambert is on vacation but I think we'll just move to 7.5

**Comment by borzel** [comment]
@stormi can you ping me, when you are ready to finally ship XCP-ng 7.5? I'll try to get some additional fixes/enhancements into XCP-ng Center 7.5.1

Here's my Milestone: https://github.com/xcp-ng/xenadmin/milestone/7

**Comment by stormi** [comment]
@borzel I will

**Comment by stormi** [comment]
@borzel We'll soon release a release candidate of 7.5. Do you have a new installer that you want me to include?

**Comment by borzel** [comment]
@stormi here you go: https://builds.schulzalex.de/xcp-ng/7.5/XCP-ng-Center-7.5.0.8.msi

**Comment by amorozov79** [comment]
andrei@andrei-HP-Compaq-8200-Elite-CMT-PC ~/.wine/drive_c/Program Files/XCP-ng Center $ wine XCP-ng\ Center.exe 

Unhandled Exception:
System.TypeInitializationException: The type initializer for 'XenAdmin.Program' threw an exception. ---> System.TypeInitializationException: The type initializer for 'XenAdmin.Core.FormFontFixer' threw an exception. ---> System.ArgumentException: The requested FontFamily could not be found [GDI+ status: FontFamilyNotFound]
  at System.Drawing.GDIPlus.CheckStatus (Status status) <0x2762b28 + 0x007ef> in <filename unknown>:0 
  at System.Drawing.FontFamily..ctor (GenericFontFamilies genericFamily) <0x27663d0 + 0x0008b> in <filename unknown>:0 
  at (wrapper remoting-invoke-with-check) System.Drawing.FontFamily:.ctor (System.Drawing.Text.GenericFontFamilies)
  at System.Drawing.FontFamily.get_GenericSansSerif () <0x2766330 + 0x0002b> in <filename unknown>:0 
  at System.Drawing.Font.CreateFont (System.String familyName, Single emSize, FontStyle style, GraphicsUnit unit, Byte charSet, Boolean isVertical) <0x2762638 + 0x00073> in <filename unknown>:0 
  at System.Drawing.Font..ctor (System.String familyName, Single emSize, FontStyle style, GraphicsUnit unit, Byte gdiCharSet, Boolean gdiVerticalFont) <0x27625c8 + 0x0004f> in <filename unknown>:0 
  at System.Drawing.Font..ctor (System.String familyName, Single emSize, System.String systemName) <0x2762550 + 0x0003f> in <filename unknown>:0 
  at (wrapper remoting-invoke-with-check) System.Drawing.Font:.ctor (string,single,string)
  at System.Drawing.SystemFonts.get_DialogFont () <0x2762460 + 0x0003f> in <filename unknown>:0 
  at XenAdmin.Core.FormFontFixer..cctor () <0x2761a50 + 0x001eb> in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at (wrapper managed-to-native) System.Object:__icall_wrapper_mono_generic_class_init (intptr)
  at XenAdmin.Program..cctor () <0x27435d0 + 0x001d7> in <filename unknown>:0 
  --- End of inner exception stack trace ---
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeInitializationException: The type initializer for 'XenAdmin.Program' threw an exception. ---> System.TypeInitializationException: The type initializer for 'XenAdmin.Core.FormFontFixer' threw an exception. ---> System.ArgumentException: The requested FontFamily could not be found [GDI+ status: FontFamilyNotFound]
  at System.Drawing.GDIPlus.CheckStatus (Status status) <0x2762b28 + 0x007ef> in <filename unknown>:0 
  at System.Drawing.FontFamily..ctor (GenericFontFamilies genericFamily) <0x27663d0 + 0x0008b> in <filename unknown>:0 
  at (wrapper remoting-invoke-with-check) System.Drawing.FontFamily:.ctor (System.Drawing.Text.GenericFontFamilies)
  at System.Drawing.FontFamily.get_GenericSansSerif () <0x2766330 + 0x0002b> in <filename unknown>:0 
  at System.Drawing.Font.CreateFont (System.String familyName, Single emSize, FontStyle style, GraphicsUnit unit, Byte charSet, Boolean isVertical) <0x2762638 + 0x00073> in <filename unknown>:0 
  at System.Drawing.Font..ctor (System.String familyName, Single emSize, FontStyle style, GraphicsUnit unit, Byte gdiCharSet, Boolean gdiVerticalFont) <0x27625c8 + 0x0004f> in <filename unknown>:0 
  at System.Drawing.Font..ctor (System.String familyName, Single emSize, System.String systemName) <0x2762550 + 0x0003f> in <filename unknown>:0 
  at (wrapper remoting-invoke-with-check) System.Drawing.Font:.ctor (string,single,string)
  at System.Drawing.SystemFonts.get_DialogFont () <0x2762460 + 0x0003f> in <filename unknown>:0 
  at XenAdmin.Core.FormFontFixer..cctor () <0x2761a50 + 0x001eb> in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at (wrapper managed-to-native) System.Object:__icall_wrapper_mono_generic_class_init (intptr)
  at XenAdmin.Program..cctor () <0x27435d0 + 0x001d7> in <filename unknown>:0 
  --- End of inner exception stack trace ---

**Comment by stormi** [comment]
@borzel Can you publish it as a release to https://github.com/xcp-ng/xenadmin so that I can reference the URL in the RPM spec file?

**Comment by borzel** [comment]
@stormi https://github.com/xcp-ng/xenadmin/releases/tag/v7.5.0

**Comment by stormi** [comment]
@borzel Thanks. It would have been even better if the version number would match that of the tag (or the reverse), but that will do!

**Comment by borzel** [comment]
@stormi hmm... I plan to use and show all 4 numbers (https://github.com/xcp-ng/xenadmin/issues/81) ... sometimes in future ;-)

**Comment by stormi** [comment]
@borzel package ready: https://updates.xcp-ng.org/7/dev/base/x86_64/Packages/xcp-ng-center-7.5.0.8-2.noarch.rpm

**Comment by borzel** [comment]
@stormi the README file in the guest-tools.iso contains the words "...when runnig on XenServer." in the last paragraph. Maybe you can change that to a more suitable term? ;-)

**Comment by stormi** [comment]
@borzel Thanks. Fixed.
